export const data = [
  {
    id: "1",
    city: "Hà Nội",
    code: ["29", "30", "31", "32", "33", "40"],
  },
  {
    id: "2",
    city: "Thái Nguyên",
    code: "20",
  },
  {
    id: "3",
    city: "Phú Thọ",
    code: "19",
  },
  {
    id: "4",
    city: "Bắc Giang",
    code: "98",
  },
  {
    id: "5",
    city: "Hòa bình",
    code: "28",
  },
  {
    id: "6",
    city: "Bắc Ninh",
    code: "99",
  },
  {
    id: "7",
    city: "Hà Nam",
    code: "90",
  },
  {
    id: "8",
    city: "Hải Dương",
    code: "34",
  },
  {
    id: "9",
    city: "Hưng Yên",
    code: "89",
  },
  {
    id: "10",
    city: "Vĩnh Phúc",
    code: "88",
  },
  {
    id: "11",
    city: "Quảng Ninh",
    code: "14",
  },
  {
    id: "12",
    city: "Hải Phòng",
    code: ["15", "16"],
  },
  {
    id: "13",
    city: "Nam Định",
    code: "18",
  },
  {
    id: "14",
    city: "Ninh Bình",
    code: "35",
  },
  {
    id: "15",
    city: "Thái Bình",
    code: "17",
  },
  {
    id: "16",
    city: "Hà Giang",
    code: "23",
  },
  {
    id: "17",
    city: "Cao Bằng",
    code: "11",
  },
  {
    id: "18",
    city: "Lào Cai",
    code: "24",
  },
  {
    id: "19",
    city: "Bắc Cạn",
    code: "97",
  },
  {
    id: "20",
    city: "Lạng Sơn",
    code: "12",
  },
  {
    id: "21",
    city: "Tuyên Quang",
    code: "22",
  },
  {
    id: "22",
    city: "Yên Bái",
    code: "21",
  },
  {
    id: "23",
    city: "Điện Biên",
    code: "27",
  },
  {
    id: "24",
    city: "Lai Châu",
    code: "25",
  },
  {
    id: "25",
    city: "Sơn La",
    code: "26",
  },
  { id: "26", city: "Thanh Hóa", code: "36" },
  { id: "27", city: "Nghệ An", code: "37" },
  { id: "28", city: "Hà Tĩnh", code: "38" },
  { id: "29", city: "Quảng Bình", code: "73" },
  { id: "30", city: "Quảng Trị", code: "74" },
  { id: "31", city: "Thừa Thiên Huế", code: "75" },
  { id: "32", city: "Đà Nẵng", code: "43" },
  { id: "33", city: "Quảng Nam", code: "92" },
  { id: "34", city: "Quảng Ngãi", code: "76" },
  { id: "35", city: "Bình Định", code: "77" },
  { id: "36", city: "Phú Yên", code: "78" },
  { id: "37", city: "Khánh Hòa", code: "79" },
  { id: "38", city: "Ninh Thuận", code: "85" },
  { id: "39", city: "Bình Thuận", code: "86" },
  { id: "40", city: "Kon Tum", code: "82" },
  { id: "41", city: "Gia Lai", code: "81" },
  { id: "42", city: "Đắk Lắk", code: "47" },
  { id: "43", city: "Đắk Nông", code: "48" },
  {
    id: "44",
    city: "Lâm Đồng",
    code: "49",
  },
  {
    id: "45",
    city: "Hồ Chí Minh",
    code: ["41", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"],
  },
  {
    id: "46",
    city: "Bình Phước",
    code: "93",
  },
  {
    id: "47",
    city: "Bình Dương",
    code: "61",
  },
  {
    id: "48",
    city: "Đồng Nai",
    code: "39, 60",
  },
  {
    id: "49",
    city: "Tây Ninh",
    code: "70",
  },
  {
    id: "50",
    city: "Bà Rịa Vũng Tàu",
    code: "72",
  },
  {
    id: "51",
    city: "Cần Thơ",
    code: "65",
  },
  {
    id: "52",
    city: "Long An",
    code: "62",
  },
  {
    id: "53",
    city: "Đồng Tháp",
    code: "66",
  },
  {
    id: "54",
    city: "Tiền Giang",
    code: "63",
  },
  {
    id: "55",
    city: "An Giang",
    code: "67",
  },
  {
    id: "56",
    city: "Bến Tre",
    code: "71",
  },
  {
    id: "57",
    city: "Vĩnh Long",
    code: "64",
  },
  {
    id: "58",
    city: "Hậu Giang",
    code: "95",
  },
  {
    id: "59",
    city: "Kiên Giang",
    code: "68",
  },
  {
    id: "60",
    city: "Sóc Trăng",
    code: "83",
  },
  {
    id: "61",
    city: "Trà Vinh",
    code: "84",
  },
  {
    id: "62",
    city: "Bạc Liêu",
    code: "94",
  },
  {
    id: "63",
    city: "Cà Mau",
    code: "69",
  },
];
